import { Document } from "./document";
import { PagePropsDesc } from "qtk";
import { ParticlesViewModal } from "../particles-view-modal";
import { ItemsStorage, ValidationResult } from "qtk";
import { IParticlesViewModal } from "../iparticles-view-modal";
export declare class ProtonViewModal extends ParticlesViewModal {
    canvas: any;
    protected fileName: string;
    protected protonEmitter: any;
    protected storage: ItemsStorage;
    protected docList: Array<string>;
    protected renderer: any;
    protected doc: Document;
    getFormatList(): Array<string>;
    getDocList(): Array<string>;
    saveDoc(fileName: string): void;
    createDoc(templateName: string): void;
    removeDoc(fileName: string): void;
    openDoc(fileName: string): void;
    exportDoc(format: string): string;
    getDocName(): string;
    getPropsDesc(): Array<PagePropsDesc>;
    setProp(path: string, value: any, converter?: string, validationRule?: string): ValidationResult;
    constructor(storage: ItemsStorage);
    protected registerCommands(): void;
    protected createEmitter(): void;
    getTemplateList(): Array<string>;
    static TYPE: string;
    static proton: any;
    static update(): void;
    static create(options: any): IParticlesViewModal;
}
